# About Dataset
The dataset captures customer satisfaction scores for a one-month period at an e-commerce platform called Shopzilla (a pseudonym). It includes various features such as category and sub-category of interaction, customer remarks, survey response date, category, item price, agent details (name, supervisor, manager), and CSAT score etc.

# Data Description:

**Column Name	Description**




### Dataset Information:
Rows: 85,907

Columns: 20

  - `Unique id`: Unique identifier for each record
  - `Channel name	`: Name of the customer service channel
  - `Categoryr`: Category of the interaction
  - `Sub-category`: Sub-category of the interaction
  - `Customer Remarks`:Feedback provided by the customer.
  - `Order id`: Identifier for the order associated with the interaction.
  - `Order date time`: Reported cause of the accident.
  - `Issue reported at`: Timestamp when the issue was reported


  - `Issue responded`: Timestamp when the issue was responded to
  - `Survey response date	`: Date of the customer survey response
  - `Customer city`: City of the customer
  - `Product category`: Category of the product
  - `Item price	`:Price of the item
  - `Connected handling time`: Time taken to handle the interaction
  - `Agent name`: Name of the customer service agent
  - `Supervisor`: Name of the supervisor


  - `Manager	`:Name of the manager
  - `Tenure Bucket`: Bucket categorizing agent tenure
  - `Agent Shift`: Shift timing of the agent
  - `CSAT Score`: Customer Satisfaction (CSAT) score

####Dataset link: https://www.kaggle.com/datasets/ddosad/ecommerce-customer-service-satisfaction

##Usage:
This dataset serves as a valuable resource for conducting Exploratory data analysis (EDA), Visualization, and Machine Learning Classification tasks pertaining to customer service performance evaluation, satisfaction forecasting, and customer behavior analysis within the e-commerce sector.

# Import Libraries

In [ ]:
# Data handling
import pandas as pd
import numpy as np

##Overview of Pandas



* Primary Function: Data manipulation and analysis, particularly for tabular data.

*   Core Structures: Utilizes Series and DataFrame as the main data structures.


*   Data Reading: Supports reading data from CSV, Excel, JSON, SQL, and other formats.

*   Data Cleaning: Provides tools to handle missing values, clean, and preprocess data.



*   Statistical Analysis: Offers functions for statistical analysis and descriptive statistics.



*   Data Manipulation: Allows filtering, sorting, grouping, and merging datasets.



*   Visualization: Integrates with visualization libraries like Matplotlib and Seaborn for data visualization.


##Overview of NumPy



*   Primary Function: High-performance mathematical and scientific operations on arrays and numbers.

*   Core Structure: Utilizes the ndarray structure for representing multi-dimensional arrays.


*   Performance: Written in C, making mathematical operations fast and efficient.

*   Mathematical Operations: Provides a wide range of mathematical and statistical functions.



*   Integration: Easily integrates with other libraries such as Pandas, Matplotlib, and SciPy.



*   Handling Missing Data: Offers functions to manage missing values within arrays.



*   Random Generation: Includes a module for generating random numbers and random arrays.

## Load Data

In [ ]:
df=pd.read_csv('/content/Customer_support_data.csv')

#Exploratory Data Analysis (EDA)

In [ ]:
# Dataset information
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 58390 entries, 0 to 58389
Data columns (total 20 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   Unique id                58390 non-null  object
 1   channel_name             58389 non-null  object
 2   category                 58389 non-null  object
 3   Sub-category             58389 non-null  object
 4   Customer Remarks         19530 non-null  object
 5   Order_id                 43001 non-null  object
 6   order_date_time          13224 non-null  object
 7   Issue_reported at        58389 non-null  object
 8   issue_responded          58389 non-null  object
 9   Survey_response_Date     58389 non-null  object
 10  Customer_City            13138 non-null  object
 11  Product_category         13213 non-null  object
 12  Item_price               13218 non-null  float64
 13  connected_handling_time  223 non-null    float64
 14  Agent_name               58389 non-null  object
 15  Supervisor               58389 non-null  object
 16  Manager                  58389 non-null  object
 17  Tenure Bucket            58389 non-null  object
 18  Agent Shift              58389 non-null  object
 19  CSAT Score               58389 non-null  float64
dtypes: float64(3), object(17)
memory usage: 8.9+ MB

In [ ]:
# Format of the data set
df.shape

(58390, 20)

In [ ]:
# The first few rows
df.head()

/usr/local/lib/python3.10/dist-packages/google/colab/_dataframe_summarizer.py:88: UserWarning: Parsing dates in %d/%m/%Y %H:%M format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  cast_date_col = pd.to_datetime(column, errors="coerce")

,Unique id,channel_name,category,Sub-category,Customer Remarks,Order_id,order_date_time,Issue_reported at,issue_responded,Survey_response_Date,Customer_City,Product_category,Item_price,connected_handling_time,Agent_name,Supervisor,Manager,Tenure Bucket,Agent Shift,CSAT Score
0,7e9ae164-6a8b-4521-a2d4-58f7c9fff13f,Outcall,Product Queries,Life Insurance,NaN,c27c9bb4-fa36-4140-9f1f-21009254ffdb,NaN,01/08/2023 11:13,01/08/2023 11:47,01-Aug-23,NaN,NaN,NaN,NaN,Richard Buchanan,Mason Gupta,Jennifer Nguyen,On Job Training,Morning,5.0
1,b07ec1b0-f376-43b6-86df-ec03da3b2e16,Outcall,Product Queries,Product Specific Information,NaN,d406b0c7-ce17-4654-b9de-f08d421254bd,NaN,01/08/2023 12:52,01/08/2023 12:54,01-Aug-23,NaN,NaN,NaN,NaN,Vicki Collins,Dylan Kim,Michael Lee,>90,Morning,5.0
2,200814dd-27c7-4149-ba2b-bd3af3092880,Inbound,Order Related,Installation/demo,NaN,c273368d-b961-44cb-beaf-62d6fd6c00d5,NaN,01/08/2023 20:16,01/08/2023 20:38,01-Aug-23,NaN,NaN,NaN,NaN,Duane Norman,Jackson Park,William Kim,On Job Training,Evening,5.0
3,eb0d3e53-c1ca-42d3-8486-e42c8d622135,Inbound,Returns,Reverse Pickup Enquiry,NaN,5aed0059-55a4-4ec6-bb54-97942092020a,NaN,01/08/2023 20:56,01/08/2023 21:16,01-Aug-23,NaN,NaN,NaN,NaN,Patrick Flores,Olivia Wang,John Smith,>90,Evening,5.0
4,ba903143-1e54-406c-b969-46c52f92e5df,Inbound,Cancellation,Not Needed,NaN,e8bed5a9-6933-4aff-9dc6-ccefd7dcde59,NaN,01/08/2023 10:30,01/08/2023 10:32,01-Aug-23,NaN,NaN,NaN,NaN,Christopher Sanchez,Austin Johnson,Michael Lee,0-30,Morning,5.0

In [ ]:
# Last few rows
df.tail()

,Unique id,channel_name,category,Sub-category,Customer Remarks,Order_id,order_date_time,Issue_reported at,issue_responded,Survey_response_Date,Customer_City,Product_category,Item_price,connected_handling_time,Agent_name,Supervisor,Manager,Tenure Bucket,Agent Shift,CSAT Score
58385,36708d72-31aa-4464-a5d8-04e6f1c437fc,Inbound,Returns,Wrong,NaN,cc89256c-f96d-4da2-95ca-84742ffa8a58,NaN,22/08/2023 10:01,22/08/2023 15:41,22-Aug-23,NaN,NaN,NaN,NaN,Nicole Chavez,Alexander Tanaka,Michael Lee,0-30,Evening,5.0
58386,7fefbe76-224e-4018-93a9-b16f688086c2,Inbound,Feedback,UnProfessional Behaviour,NaN,b8358187-18a0-4e19-a15a-58bdfbec2715,NaN,22/08/2023 21:21,22/08/2023 21:23,22-Aug-23,NaN,NaN,NaN,NaN,Christian Armstrong,Wyatt Kim,Michael Lee,>90,Evening,5.0
58387,1aee7968-1a51-4eaf-bc87-0143f08df07d,Outcall,Payments related,Online Payment Issues,NaN,ea714205-e7c5-4c1a-9aa6-f3d937fa30e5,NaN,22/08/2023 19:14,22/08/2023 19:39,22-Aug-23,NaN,NaN,NaN,NaN,Jenna Larson,Emily Yamashita,John Smith,61-90,Evening,5.0
58388,48d6bae1-19a3-49bc-8ce7-9636d3406ce3,Inbound,Order Related,Installation/demo,NaN,ab56c246-2eae-4fd8-88de-b080415bd423,NaN,22/08/2023 10:23,22/08/2023 15:05,22-Aug-23,NaN,NaN,NaN,NaN,Brianna Wolf,Mia Patel,John Smith,>90,Morning,5.0
58389,c0cc621e-c7f1-4203-b2da-709d4119b7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
# Descriptive statistics
df.describe()

          Item_price  connected_handling_time    CSAT Score
count   13218.000000               223.000000  58389.000000
mean     5919.607429               463.582960      4.208310
std     13233.534689               249.628699      1.409843
min         0.000000                 0.000000      1.000000
25%       399.000000               299.000000      4.000000
50%       999.000000               424.000000      5.000000
75%      2969.750000               590.500000      5.000000
max    164999.000000              1986.000000      5.000000

In [ ]:
# Descriptive statistics for categorical columns
df.describe(include='object')

,Unique id,channel_name,category,Sub-category,Customer Remarks,Order_id,order_date_time,Issue_reported at,issue_responded,Survey_response_Date,Customer_City,Product_category,Agent_name,Supervisor,Manager,Tenure Bucket,Agent Shift
count,58390,58389,58389,58389,19530,43001,13224,58389,58389,58389,13138,13213,58389,58389,58389,58389,58389
unique,58390,3,12,57,12896,43001,10582,21787,21898,22,1615,9,1363,40,6,5,5
top,7e9ae164-6a8b-4521-a2d4-58f7c9fff13f,Inbound,Returns,Reverse Pickup Enquiry,Good,c27c9bb4-fa36-4140-9f1f-21009254ffdb,09/08/2023 11:55,15/08/2023 10:59,08/08/2023 17:51,17-Aug-23,HYDERABAD,Electronics,Wendy Taylor,Elijah Yamaguchi,John Smith,>90,Morning
freq,1,47722,30746,15173,911,1,6,13,13,3193,575,3810,322,2999,18879,21949,27232

In [ ]:
# Check for duplicate rows
df.duplicated().sum()

0

In [ ]:
# Check for missing values
df.isnull().sum()

Unique id                      0
channel_name                   1
category                       1
Sub-category                   1
Customer Remarks           38860
Order_id                   15389
order_date_time            45166
Issue_reported at              1
issue_responded                1
Survey_response_Date           1
Customer_City              45252
Product_category           45177
Item_price                 45172
connected_handling_time    58167
Agent_name                     1
Supervisor                     1
Manager                        1
Tenure Bucket                  1
Agent Shift                    1
CSAT Score                     1
dtype: int64


# Data Preprocessing

Data preprocessing is a crucial step in the data analysis and machine learning pipeline. It involves cleaning, transforming, and organizing raw data into a suitable format for analysis. Here are some key steps and techniques in data preprocessing:

1. Data Cleaning


*   Handling Missing Values: Addressing missing data by removing rows/columns with missing values or filling them using various strategies.

In [ ]:
#1.Remove missing values:
df = df.dropna(subset=['connected_handling_time'])
df = df.dropna(subset=['Customer Remarks'])

In [ ]:
#2. Fill empty values ​​with column average
df['Item_price'].fillna(df['Item_price'].mean(), inplace=True)
df['connected_handling_time'].fillna(df['connected_handling_time'].mean(), inplace=True)

<ipython-input-12-53b5f4b66419>:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Item_price'].fillna(df['Item_price'].mean(), inplace=True)
<ipython-input-12-53b5f4b66419>:3: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['connected_handling_time'].fillna(df['connected_handling_time'].mean(), inplace=True)

In [ ]:
#3. Fill empty values ​​with highest repeat value (mode)
df['Customer Remarks'].fillna(df['Customer Remarks'].mode()[0], inplace=True)
df['Order_id'].fillna(df['Order_id'].mode()[0], inplace=True)
df['order_date_time'].fillna(df['order_date_time'].mode()[0], inplace=True)
df['Customer_City'].fillna(df['Customer_City'].mode()[0], inplace=True)
df['Product_category'].fillna(df['Product_category'].mode()[0], inplace=True)

<ipython-input-13-676c0b4331ba>:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Customer Remarks'].fillna(df['Customer Remarks'].mode()[0], inplace=True)
<ipython-input-13-676c0b4331ba>:3: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Order_id'].fillna(df['Order_id'].mode()[0], inplace=True)
<ipython-input-13-676c0b4331ba>:4: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['order_date_time'].fillna(df['order_date_time'].mode()[0], inplace=True)
<ipython-input-13-676c0b4331ba>:5: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Customer_City'].fillna(df['Customer_City'].mode()[0], inplace=True)
<ipython-input-13-676c0b4331ba>:6: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Product_category'].fillna(df['Product_category'].mode()[0], inplace=True)

In [ ]:
df.isnull().sum()

Unique id                  0
channel_name               0
category                   0
Sub-category               0
Customer Remarks           0
Order_id                   0
order_date_time            0
Issue_reported at          0
issue_responded            0
Survey_response_Date       0
Customer_City              0
Product_category           0
Item_price                 0
connected_handling_time    0
Agent_name                 0
Supervisor                 0
Manager                    0
Tenure Bucket              0
Agent Shift                0
CSAT Score                 0
dtype: int64

In [ ]:
#4.Remove outliers:
from scipy import stats
z_scores = np.abs(stats.zscore(df['connected_handling_time']))
df = df[(z_scores < 3)]

In [ ]:
df.head(10)

,Unique id,channel_name,category,Sub-category,Customer Remarks,Order_id,order_date_time,Issue_reported at,issue_responded,Survey_response_Date,Customer_City,Product_category,Item_price,connected_handling_time,Agent_name,Supervisor,Manager,Tenure Bucket,Agent Shift,CSAT Score
8501,225ff7cd-0906-46c9-b259-046e01700f3c,Inbound,Shopzilla Related,Shopzila Premium Related,Pathetic customer care,0258d703-8287-428d-9e48-446e29eec3e5,01/08/2023 10:48,04/08/2023 17:11,04/08/2023 21:56,04-Aug-23,BARASAT,Electronics,879.135135,0.0,Robert Lara,Brayden Wong,John Smith,31-60,Evening,1.0
9666,4adaaef1-0f9c-4c93-b175-3b692deed437,Outcall,Cancellation,Return cancellation,Thanks for all of you.,7dac1162-3426-4559-baf2-2507e4f33e15,01/08/2023 10:48,05/08/2023 17:04,05/08/2023 17:07,05-Aug-23,BARASAT,Electronics,879.135135,240.0,Jasmine Maxwell,Olivia Wang,Olivia Tan,>90,Morning,5.0
10469,a1126df4-f5fb-4b9b-b058-700344db690b,Outcall,Returns,Return request,no,7e5034ba-8e29-48b9-b891-4f31238fea68,01/08/2023 10:48,05/08/2023 14:13,05/08/2023 14:15,05-Aug-23,BARASAT,Electronics,879.135135,368.0,James Mcgee,Madison Kim,John Smith,>90,Morning,5.0
11104,1dc9d36e-f5e5-4942-a306-d0915979d084,Outcall,Cancellation,Return cancellation,Very bad experience,094f42ac-f316-459d-8bda-5b7c8366bf3b,01/08/2023 10:48,05/08/2023 12:07,05/08/2023 12:35,05-Aug-23,BARASAT,Electronics,879.135135,174.0,Kathleen Williams,Mason Gupta,Olivia Tan,>90,Morning,1.0
11313,b23a7638-00d8-4471-9577-48b30dafc4d1,Outcall,Returns,Return request,Good support. ...and one more thing they were...,fd886c24-2e85-4afc-8ae4-7a386f42fb31,01/08/2023 10:48,05/08/2023 19:33,05/08/2023 19:46,05-Aug-23,BARASAT,Electronics,879.135135,464.0,Katrina White,Mia Patel,Olivia Tan,0-30,Morning,3.0
12131,1cf5a60a-7bf7-489f-aad0-57b41bfb375f,Outcall,Returns,Return request,Good customer executive,be760534-201d-4ede-b162-1ffc6afe7642,01/08/2023 10:48,05/08/2023 10:10,05/08/2023 10:26,05-Aug-23,BARASAT,Electronics,879.135135,722.0,Katrina White,Mia Patel,Olivia Tan,0-30,Morning,5.0
12722,2bf33e7e-98d1-4426-9210-b2af108fcfd5,Outcall,Cancellation,Return cancellation,Please try to give refund,d2a90adf-e95f-4be6-abe0-8736ead15fdf,01/08/2023 10:48,05/08/2023 13:20,05/08/2023 13:36,05-Aug-23,BARASAT,Electronics,879.135135,1066.0,Katelyn Horton,Mason Gupta,Olivia Tan,0-30,Morning,4.0
12986,cf1655c6-743e-4a3e-9498-009b6b09b056,Outcall,Cancellation,Return cancellation,The customer support person was really amazing...,1b617ab4-178b-40a8-b5ee-9123b3979265,01/08/2023 10:48,05/08/2023 13:51,05/08/2023 18:27,05-Aug-23,BARASAT,Electronics,879.135135,711.0,Jordan Wilson,Abigail Suzuki,Jennifer Nguyen,On Job Training,Morning,5.0
13532,d350d798-cbce-42b4-afb2-436a8d8202ea,Outcall,Returns,Return request,Please improve the return policy,0f9703e0-5ed1-413b-90df-0c76dec12740,01/08/2023 10:48,05/08/2023 17:18,05/08/2023 17:39,05-Aug-23,BARASAT,Electronics,879.135135,957.0,Christopher Anderson,Mason Gupta,Olivia Tan,0-30,Afternoon,4.0
13565,08c6a929-a403-4f14-810f-2275fe591230,Outcall,Returns,Return request,Good,0258d703-8287-428d-9e48-446e29eec3e5,29/07/2023 03:44,05/08/2023 11:11,05/08/2023 11:50,05-Aug-23,BETTIAH,Electronics,899.000000,367.0,Katelyn Horton,Mason Gupta,Olivia Tan,0-30,Morning,5.0

In [ ]:
# finding null values and unique value counts
null_values= round(df.isnull().sum() * 100 / len(df),2)
unique_values=df.nunique()
analysis_df = pd.DataFrame({'column_name': df.columns,"unique_values": unique_values,'null_values_%': null_values,"data_type":df.dtypes})
analysis_df.reset_index(drop=True,inplace=True)
analysis_df

                column_name  unique_values  null_values_% data_type
0                 Unique id             74            0.0    object
1              channel_name              2            0.0    object
2                  category              5            0.0    object
3              Sub-category              9            0.0    object
4          Customer Remarks             67            0.0    object
5                  Order_id             66            0.0    object
6           order_date_time             37            0.0    object
7         Issue_reported at             72            0.0    object
8           issue_responded             74            0.0    object
9      Survey_response_Date             14            0.0    object
10            Customer_City             34            0.0    object
11         Product_category              2            0.0    object
12               Item_price             12            0.0   float64
13  connected_handling_time             72            0.0   float64
14               Agent_name             37            0.0    object
15               Supervisor             14            0.0    object
16                  Manager              5            0.0    object
17            Tenure Bucket              4            0.0    object
18              Agent Shift              4            0.0    object
19               CSAT Score              5            0.0   float64

In [ ]:
# تحويل الأعمدة الزمنية إلى datetime
df['order_date_time'] = pd.to_datetime(df['order_date_time'], errors='coerce')
df['Survey_response_Date'] = pd.to_datetime(df['Survey_response_Date'], errors='coerce')

<ipython-input-18-28274b6761b9>:3: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df['Survey_response_Date'] = pd.to_datetime(df['Survey_response_Date'], errors='coerce')

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 74 entries, 8501 to 55265
Data columns (total 20 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   Unique id                74 non-null     object
 1   channel_name             74 non-null     object
 2   category                 74 non-null     object
 3   Sub-category             74 non-null     object
 4   Customer Remarks         74 non-null     object
 5   Order_id                 74 non-null     object
 6   order_date_time          66 non-null     datetime64[ns]
 7   Issue_reported at        74 non-null     object
 8   issue_responded          74 non-null     object
 9   Survey_response_Date     74 non-null     datetime64[ns]
 10  Customer_City            74 non-null     object
 11  Product_category         74 non-null     object
 12  Item_price               74 non-null     float64
 13  connected_handling_time  74 non-null     float64
 14  Agent_name               74 non-null     object
 15  Supervisor               74 non-null     object
 16  Manager                  74 non-null     object
 17  Tenure Bucket            74 non-null     object
 18  Agent Shift              74 non-null     object
 19  CSAT Score               74 non-null     float64
dtypes: datetime64[ns](2), float64(3), object(15)
memory usage: 14.2+ KB

In [ ]:
df.head(1)

,Unique id,channel_name,category,Sub-category,Customer Remarks,Order_id,order_date_time,Issue_reported at,issue_responded,Survey_response_Date,Customer_City,Product_category,Item_price,connected_handling_time,Agent_name,Supervisor,Manager,Tenure Bucket,Agent Shift,CSAT Score
8501,225ff7cd-0906-46c9-b259-046e01700f3c,Inbound,Shopzilla Related,Shopzila Premium Related,Pathetic customer care,0258d703-8287-428d-9e48-446e29eec3e5,2023-01-08 10:48:00,04/08/2023 17:11,04/08/2023 21:56,2023-08-04,BARASAT,Electronics,879.135135,0.0,Robert Lara,Brayden Wong,John Smith,31-60,Evening,1.0